name: Daily Scheduled Commit

# Run daily at 04:30 UTC (cron: '30 4 * * *').
# Also allow manual runs from the Actions tab.
on:
  schedule:
    - cron: '18 1 * * *'
  workflow_dispatch: {}

# Ensure the workflow can push commits back to the repository.
permissions:
  contents: write

jobs:
  daily_update:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository so the job can access and push changes.
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Add Daily Commit - 24f2000604@ds.study.iitm.ac.in
        run: |
          # Configure Git user for the commit (use your preferred name/email).
          git config user.name "24f2000604 (GitHub Actions)"
          git config user.email "24f2000604@ds.study.iitm.ac.in"

          # Create/update a file with the current UTC timestamp.
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Last run at: $TIMESTAMP" > last_daily_run.txt

          # Add and commit only if there are changes.
          git add last_daily_run.txt
          if git diff --cached --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "SCHEDULER: Daily commit triggered at $TIMESTAMP"
            # Push the commit back to the branch the workflow checked out (HEAD).
            git push origin HEAD
          fi
